#party set debug on
#party set bestof 2
# party kom database/_posts/2020/12/02/Innsbruck_results_sprints_and_kom.txt foo.md race1
# party kom database/_posts/2020/12/02/Innsbruck_results_sprints_and_kom.txt foo.md race1 0
# party sprints database/_posts/2020/12/03/Tempoish-Thursday-Sprints_sprints.txt foo.md race2 1
party sprints database/_posts/2020/12/03/Tempoish-Thursday-Sprints_sprints.txt foo.md race1 0
# party results database/_posts/2020/12/04/Jungle-Circuit-On-A-MTB_results.txt foo.md race3 2
party show
quit
