# party convert database/_posts/2020/12/01/A-Smack-down-on-Petit-KOM_results_zwift.txt database/_posts/2020/12/01/A-Smack-down-on-Petit-KOM_results_partytime.txt
party convert database/_posts/2020/12/02/Innsbruck_results_results_zwift.txt database/_posts/2020/12/02/Innsbruck_results_results_partytime.txt
#party convert2 database/_posts/2020/12/03/Tempoish-Thursday-Sprints_results_zwift.txt database/_posts/2020/12/03/Tempoish-Thursday-Sprints_results_partytime.txt
#party convert database/_posts/2020/12/04/Jungle-Circuit-On-A-MTB_results_zwift.txt database/_posts/2020/12/04/Jungle-Circuit-On-A-MTB_results_partytime.txt
