#party set bestof 5
party set bestof 2
party set cat 1
party set cat1 10.3
party set cat2 11.0
party set cat3 11.0
party set calendar on
party kom database/_posts/2020/12/10/2020-12-10-Another-Morning-Of-Sprints_sprints.txt foo.md 20-12-10 0
party kom database/_posts/2020/12/17/2020-12-17-Alpe-Tomorrow-U-Ready_kom.txt foo.md 20-12-17 1
party kom database/_posts/2020/12/31/2020-12-31-Another-fun-sprint-day-kom.txt foo.md 20-12-31 2
party kom database/_posts/2021/01/07/2021-01-07-Another-fun-sprint-day-kom.txt foo.md 21-01-07 3
party kom database/_posts/2021/01/14/2021-01-14-Tempoish-funday-kom.txt foo.md 21-01-14 4
party kom database/_posts/2021/01/21/2021-01-21-No-sleep-til-Brooklyn-kom.txt foo.md 21-01-21 5
# party show
party set clip on
#party set PR on
party tempoish
party reset list
party set bestof 2
party set cat 2
party set cat1 10.3
party set cat2 11.0
party set cat3 11.0
party set calendar on
party kom database/_posts/2020/12/10/2020-12-10-Another-Morning-Of-Sprints_sprints.txt foo.md 20-12-10 0
party kom database/_posts/2020/12/17/2020-12-17-Alpe-Tomorrow-U-Ready_kom.txt foo.md 20-12-17 1
party kom database/_posts/2020/12/31/2020-12-31-Another-fun-sprint-day-kom.txt foo.md 20-12-31 2
party kom database/_posts/2021/01/07/2021-01-07-Another-fun-sprint-day-kom.txt foo.md 21-01-07 3
party kom database/_posts/2021/01/14/2021-01-14-Tempoish-funday-kom.txt foo.md 21-01-14 4
party kom database/_posts/2021/01/21/2021-01-21-No-sleep-til-Brooklyn-kom.txt foo.md 21-01-21 5
# party show
party set clip on
#party set PR on
party tempoish
party reset list
party set bestof 2
party set cat 3
party set cat1 10.3
party set cat2 11.0
party set cat3 11.0
party set calendar on
party kom database/_posts/2020/12/10/2020-12-10-Another-Morning-Of-Sprints_sprints.txt foo.md 20-12-10 0
party kom database/_posts/2020/12/17/2020-12-17-Alpe-Tomorrow-U-Ready_kom.txt foo.md 20-12-17 1
party kom database/_posts/2020/12/31/2020-12-31-Another-fun-sprint-day-kom.txt foo.md 20-12-31 2
party kom database/_posts/2021/01/07/2021-01-07-Another-fun-sprint-day-kom.txt foo.md 21-01-07 3
party kom database/_posts/2021/01/14/2021-01-14-Tempoish-funday-kom.txt foo.md 21-01-14 4
party kom database/_posts/2021/01/21/2021-01-21-No-sleep-til-Brooklyn-kom.txt foo.md 21-01-21 5
# party show
party set clip on
#party set PR on
party tempoish
quit
