#party set bestof 5
party set bestof 2
party set cat 1
party set cat1 10.3
party set cat2 11.0
party set cat3 11.0
party set group All
party kom database/_posts/2021/01/21/2021-01-21-No-sleep-til-Brooklyn-kom.txt foo.md 21-01-21 6
party set snap All
#party set lockdown on
party kom database/_posts/2020/12/03/Tempoish-Thursday-Sprints_sprints.txt foo.md 20-12-03 0
party kom database/_posts/2020/12/10/2020-12-10-Another-Morning-Of-Sprints_sprints.txt foo.md 20-12-10 1
party kom database/_posts/2020/12/17/2020-12-17-Alpe-Tomorrow-U-Ready_kom.txt foo.md 20-12-17 2
party kom database/_posts/2020/12/31/2020-12-31-Another-fun-sprint-day-kom.txt foo.md 20-12-31 3
party kom database/_posts/2021/01/07/2021-01-07-Another-fun-sprint-day-kom.txt foo.md 21-01-07 4
party kom database/_posts/2021/01/14/2021-01-14-Tempoish-funday-kom.txt foo.md 21-01-14 5
# party show
party set clip on
#party set PR on
party set calendar on
party tempoish
quit
# party time
party reset list
party set bestof 2
party set cat 2
party set cat1 10.3
party set cat2 11.0
party set cat3 11.0
party set group All
party kom database/_posts/2021/01/21/2021-01-21-No-sleep-til-Brooklyn-kom.txt foo.md 21-01-21 6
party set snap All
#party set lockdown on
party kom database/_posts/2020/12/03/Tempoish-Thursday-Sprints_sprints.txt foo.md 20-12-03 0
party kom database/_posts/2020/12/10/2020-12-10-Another-Morning-Of-Sprints_sprints.txt foo.md 20-12-10 1
party kom database/_posts/2020/12/17/2020-12-17-Alpe-Tomorrow-U-Ready_kom.txt foo.md 20-12-17 2
party kom database/_posts/2020/12/31/2020-12-31-Another-fun-sprint-day-kom.txt foo.md 20-12-31 3
party kom database/_posts/2021/01/07/2021-01-07-Another-fun-sprint-day-kom.txt foo.md 21-01-07 4
party kom database/_posts/2021/01/14/2021-01-14-Tempoish-funday-kom.txt foo.md 21-01-14 5
# party show
party set clip on
#party set PR on
party set calendar on
party tempoish
# party time
party reset list
party set bestof 2
party set cat 3
party set cat1 10.3
party set cat2 11.0
party set cat3 11.0
party set group All
party kom database/_posts/2021/01/21/2021-01-21-No-sleep-til-Brooklyn-kom.txt foo.md 21-01-21 6
party set snap All
#party set lockdown on
party kom database/_posts/2020/12/03/Tempoish-Thursday-Sprints_sprints.txt foo.md 20-12-03 0
party kom database/_posts/2020/12/10/2020-12-10-Another-Morning-Of-Sprints_sprints.txt foo.md 20-12-10 1
party kom database/_posts/2020/12/17/2020-12-17-Alpe-Tomorrow-U-Ready_kom.txt foo.md 20-12-17 2
party kom database/_posts/2020/12/31/2020-12-31-Another-fun-sprint-day-kom.txt foo.md 20-12-31 3
party kom database/_posts/2021/01/07/2021-01-07-Another-fun-sprint-day-kom.txt foo.md 21-01-07 4
party kom database/_posts/2021/01/14/2021-01-14-Tempoish-funday-kom.txt foo.md 21-01-14 5
# party show
party set clip on
#party set PR on
party set calendar on
party tempoish
# party time
# party show
quit
