#party set max 42
#party set bestof 2
party set group B
party kom database/_posts/2021/01/11/2021-01-12-Cant-get-enough-of-the-Box-kom.txt database/_posts/2021/01/11/2021-01-12-Cant-get-enough-of-the-Box-kom-B.md race1 0
party set snap B
party set lockdown on
#party set clip on
#party set PR on
echo ********
echo ******** B RESULTS
echo ********
#party set adjust 2
#party tempoish
party show
party reset list
#party set max 42
#party set bestof 2
party set group A
party set lockdown off
party kom database/_posts/2021/01/11/2021-01-12-Cant-get-enough-of-the-Box-kom.txt database/_posts/2021/01/11/2021-01-12-Cant-get-enough-of-the-Box-kom-B.md race1 0
party set snap A
party set lockdown on
#party set clip on
#party set PR on
echo ********
echo ******** A RESULTS
echo ********
#party set adjust 2
#party tempoish
party show
quit
