party set max 42
party set bestof 2
party set group B
party kom database/_posts/2020/12/19/2020-12-29-Box-Hill_kom.txt database/_posts/2020/12/19/2020-12-29-Box-Hill_kom_columns_B.md race1
party set snap B
party set lockdown on
party kom database/_posts/2020/12/19/2020-12-31-Another-fun-sprint-day-kom.txt database/_posts/2020/12/19/2020-12-31-Another-fun-sprint-day-kom_columns_B.md race2
party results database/_posts/2021/01/01/2021-01-01-Bologna-results.txt database/_posts/2021/01/01/2021-01-01-Bologna-results_columns_B.md race3
party set clip on
party show
party reset list
party set max 35
party set bestof 2
party set group A
party set lockdown off
party kom database/_posts/2020/12/19/2020-12-29-Box-Hill_kom.txt database/_posts/2020/12/19/2020-12-29-Box-Hill_kom_columns_A.md race1
party set snap A
party set lockdown on
party kom database/_posts/2020/12/19/2020-12-31-Another-fun-sprint-day-kom.txt database/_posts/2020/12/19/2020-12-31-Another-fun-sprint-day-kom_columns_A.md race2
party results2 database/_posts/2021/01/01/2021-01-01-Bologna-results.txt database/_posts/2021/01/01/2021-01-01-Bologna-results_columns_A.md race3
party set clip on
party show
quit
