party set max 59
party set bestof 2
party set group B
party kom database/_posts/2021/01/05/2021-01-05-Another-trip-up-the-Box-kom.txt database/_posts/2021/01/05/2021-01-05-Another-trip-up-the-Box-kom-B.md race1
party set snap B
party set lockdown on
party kom database/_posts/2021/01/07/2021-01-07-Fast-day-at-the-sprints.txt database/_posts/2021/01/07/2021-01-07-Fast-day-at-the-sprints-kom-B.md race2
party kom database/_posts/2021/01/08/2021-01-08-EPIC-KOM-was-epic-kom.txt database/_posts/2021/01/08/2021-01-08-EPIC-KOM-was-epic-kom-B.md race3
party set lockdown on
party set clip on
party show
party reset list
party set group A
party set lockdown off
party kom database/_posts/2021/01/05/2021-01-05-Another-trip-up-the-Box-kom.txt database/_posts/2021/01/05/2021-01-05-Another-trip-up-the-Box-kom-A.md race1
party set snap A
party set lockdown on
party kom database/_posts/2021/01/07/2021-01-07-Fast-day-at-the-sprints.txt database/_posts/2021/01/07/2021-01-07-Fast-day-at-the-sprints-kom-A.md race2
party kom database/_posts/2021/01/08/2021-01-08-EPIC-KOM-was-epic-kom.txt database/_posts/2021/01/08/2021-01-08-EPIC-KOM-was-epic-kom-A.md race3
party set clip on
party show
quit
