party set max 35
party set bestof 2
party set group B
party kom database/_posts/2021/01/26/2021-01-26-Richmond-Libby-23rd-fun-in-the-sun-libby-kom.txt database/_posts/2021/01/26/2021-01-26-Richmond-Libby-23rd-fun-in-the-sun-libby-kom-B_columns.md libby 0
party set snap B
party set lockdown on
party kom database/_posts/2021/01/26/2021-01-26-Richmond-Libby-23rd-fun-in-the-sun-23rd-kom.txt database/_posts/2021/01/26/2021-01-26-Richmond-Libby-23rd-fun-in-the-sun-23rd-kom-B_columns.md 23rd 1
party set clip on
party set calendar on
#party set PR on
#party tempoish
#party show
party richmond
#party time
party reset list
#party set bestof 2
party set group A
party kom database/_posts/2021/01/26/2021-01-26-Richmond-Libby-23rd-fun-in-the-sun-libby-kom.txt database/_posts/2021/01/26/2021-01-26-Richmond-Libby-23rd-fun-in-the-sun-libby-kom-A_columns.md libby 0
party set snap A
party set lockdown on
party kom database/_posts/2021/01/26/2021-01-26-Richmond-Libby-23rd-fun-in-the-sun-23rd-kom.txt database/_posts/2021/01/26/2021-01-26-Richmond-Libby-23rd-fun-in-the-sun-23rd-kom-A_columns.md 23rd 1
party set clip on
party set calendar on
#party set PR on
#party tempoish
#party show
party richmond
#party time
quit
