party set max 31
party set bestof 2
party kom database/_posts/2021/01/19/2021-01-19-Gun-Fight-At-OK-Corral-kom.txt database/_posts/2021/01/19/2021-01-19-Gun-Fight-At-OK-Corral-kom_columns.md race1 0
party kom database/_posts/2021/01/21/2021-01-21-No-sleep-til-Brooklyn-kom.txt database/_posts/2021/01/21/2021-01-21-No-sleep-til-Brooklyn-kom_columns.md race2 1
party set group GRIT
party set lockdown on
party following database/_posts/2021/01/22/2021-01-22-Week-Number-8-in-the-books-results.txt database/_posts/2021/01/22/2021-01-22-Week-Number-8-in-the-books-results_columns.md  race3 2
party set clip on
party show
#party time
quit
